name: Hard Way Cinema
favicon: null
layout_spectrum: 0.08091225987300277
typography_spectrum: 0.44849675754085183
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.21323804231360555
  lightness: 0.4095640010200441
  saturation: 0.9704800012987107
  rhythmicContrast: 0.5900408320594579
purpose: []
